import type { Metadata } from "next";
import { LegalPageShell, LegalSection } from "@/components/legal/LegalPageShell";
export const metadata:Metadata={title:"Community Guidelines | UntapGo",description:"Safety, respect and honest participation rules for the UntapGo player community.",alternates:{canonical:"https://untapgo.com/community-guidelines"}};
const toc=[["purpose","Purpose"],["respect","Respect and boundaries"],["safety","Offline safety"],["honesty","Honest events and profiles"],["attendance","Attendance"],["privacy","Privacy and content"],["hosts","For hosts"],["players","For players"],["reports","Reports and enforcement"],["urgent","Urgent concerns"],["contact","Contact"]].map(([id,label])=>({id,label}));
export default function CommunityGuidelinesPage(){return <LegalPageShell title="Community Guidelines" introduction="UntapGo works when people can find a table, show up as promised and feel safe there. These rules apply to profiles, events, attendance tools and conduct connected to an UntapGo meeting." toc={toc}>
  <LegalSection id="purpose" title="1. Build a table people want to join">
    <p>UntapGo brings local Magic: The Gathering players together for offline games. Different formats, skill levels, identities and play styles belong here. The basic expectation is simple: be honest about the event you are offering, respect the people at the table and do not use the service to create risk for others.</p>
    <p>These Guidelines apply to everyone, including hosts and players. They cover activity in UntapGo and conduct at an event where it affects participant safety, trust or ability to use the service. The <a href="/terms">Terms of Service</a> contain the binding account rules.</p>
  </LegalSection>
  <LegalSection id="respect" title="2. Respect, harassment and personal boundaries">
    <h3>Treat people as people</h3><p>Disagreement about a rule, deck or play is not permission to insult, humiliate or intimidate someone. Do not target a person with repeated unwanted contact, hostile comments, stalking, bullying, doxxing or coordinated harassment.</p>
    <h3>No hate or discrimination</h3><p>Do not attack, exclude or demean people based on race, colour, ethnic or national origin, religion, disability, sex, sexual orientation, gender identity, age or another protected characteristic. Slurs, dehumanising content and calls to discriminate are not allowed. A venue’s lawful accessibility or age rules should be stated accurately; they are not a licence for prejudice.</p>
    <h3>Threats and violence</h3><p>Credible threats, encouragement of violence, glorification of harm directed at a person, bringing prohibited weapons, or using the service to plan violence are forbidden. In immediate danger, contact local emergency services—not an UntapGo report.</p>
    <h3>Sexual harassment</h3><p>Sexual comments, advances, touching, imagery or pressure without consent are not welcome. Respect a clear “no”, a request to stop and personal space. Do not use event or profile information to pursue someone who has blocked you or made clear they do not want contact.</p>
  </LegalSection>
  <LegalSection id="safety" title="3. Safety at offline events">
    <p>Choose legitimate venues suitable for tabletop play. Check opening hours, access, transport and any relevant house rules. Hosts should not publish a private address more widely than needed. Players should avoid sharing home, work, travel or contact details that are not required for the game.</p>
    <p>Meeting through UntapGo does not verify a person or guarantee their conduct. Tell someone your plans when appropriate, arrange safe transport and leave if a situation feels wrong. Minors must follow applicable age, supervision and venue requirements. Adults must not use UntapGo to create inappropriate private access to minors.</p>
    <p>Do not bring illegal items, encourage dangerous activity, tamper with someone’s belongings or knowingly create an unsafe venue condition. Hosts remain responsible for the event and venue they organise. UntapGo cannot supervise every gathering.</p>
  </LegalSection>
  <LegalSection id="honesty" title="4. Honest events, profiles and offers">
    <p>Create only real events you intend to run. State the correct time, place, capacity, format and relevant table expectations. Do not use a false or misleading location, impersonate a store or organiser, copy another person’s identity, or manufacture attendance to make an event appear established.</p>
    <p>Fraud, theft and scams are prohibited. This includes fake ticket or product offers, deceptive prize claims, payment redirection, phishing, account trading and using an event listing mainly to collect personal information. The inspected product has no built-in payment flow; be particularly cautious about off-platform payment requests.</p>
    <p>Profiles must represent the account holder. Nicknames can be creative, but must not impersonate another player, UntapGo staff, a venue or a public figure. Do not use misleading avatars or claims to evade a prior restriction.</p>
    <p>Do not spam listings, repeatedly promote unrelated products, recruit through misleading events or use player information for unsolicited marketing. Genuine venue details and event-relevant community information are welcome; unrelated commercial campaigns are not.</p>
  </LegalSection>
  <LegalSection id="attendance" title="5. Seat requests, check-in and attendance">
    <p>Request a seat when you intend to use it. If plans change, cancel early enough for another player to join. Occasional mistakes and unavoidable absences happen; repeated deliberate no-shows undermine local tables.</p>
    <p>Never scan a QR code for someone who is not present, share a live code for remote check-in, alter a URL or token, check in under another account, pressure a host to falsify status, or mark people present or absent dishonestly. Hosts should use attendance records for running the event, resolving a genuine dispute and maintaining accurate participation—not for punishment unrelated to the event.</p>
    <p>The current implementation records attendance statuses and feedback, but it does not establish an active Trust Score. These Guidelines do not claim that no-shows automatically change a score or restrict an account. Deliberate manipulation may still lead to moderation under the Terms.</p>
  </LegalSection>
  <LegalSection id="privacy" title="6. Privacy, personal information and creative work">
    <p>Do not publish someone’s private address, phone number, email, private messages, financial data, identity documents, location history or other sensitive information without authority. An event may reveal a real-world plan, so share its address only with the audience that genuinely needs it and choose a public venue where practical.</p>
    <p>Blocking restricts product interactions but cannot guarantee you will never encounter someone at a public venue. Do not attempt to bypass a block, use another account to inspect hidden information, or pressure others to disclose a blocked person’s activity. If a block relates to a credible offline threat, make a broader safety plan and contact appropriate authorities or venue staff.</p>
    <p>Only upload avatars, event text, deck resources or other material you are entitled to share. Deck lists and factual card names may involve different rights from artwork, photographs or original writing. Credit creators where appropriate and respond reasonably to a valid rights concern.</p>
    <p>Do not use UntapGo for illegal content or activity, malware, access-control bypass, harmful scraping, sale of personal data, or attempts to compromise another account or the service.</p>
  </LegalSection>
  <LegalSection id="hosts" title="7. What hosts owe their table">
    <ul><li>Use an accurate date, time, venue, capacity and game format.</li><li>Have the venue’s permission and follow its lawful rules.</li><li>Explain power level, proxy expectations, accessibility or cost information that participants need to decide whether to join.</li><li>Review requests fairly and communicate cancellations or major changes promptly.</li><li>Create a respectful table and respond proportionately to harassment or safety concerns.</li><li>Keep QR check-in available only at the venue and correct attendance mistakes where possible.</li><li>Do not reuse attendee, profile or attendance data for unrelated promotion, tracking or retaliation.</li></ul>
    <p>A host may set reasonable play and venue expectations, but may not use “house rules” to excuse discrimination, harassment, dangerous conduct or unlawful activity.</p>
  </LegalSection>
  <LegalSection id="players" title="8. What players owe their table">
    <ul><li>Send genuine requests and cancel when you cannot attend.</li><li>Read the listing and bring a deck suitable for the stated format and expectations.</li><li>Follow lawful venue and host rules and handle cards and belongings respectfully.</li><li>Do not impersonate another player or manipulate check-in, attendance, feedback or seat capacity.</li><li>Raise rules disagreements calmly and accept that a host or venue may end disruptive conduct.</li><li>Report serious concerns honestly and include only relevant detail.</li></ul>
  </LegalSection>
  <LegalSection id="reports" title="9. Reporting and enforcement">
    <p>The public-profile menu includes a report form with a reason and optional details. Use it for a specific account concern. Event feedback can record an experience with a host or player after relevant attendance conditions are met. Provide clear facts, avoid speculation and do not submit a report to punish someone for an ordinary gameplay disagreement.</p>
    <p>Abusive reporting—coordinated false reports, fabricated evidence, threats to report unless someone complies, or repeated reports of conduct that plainly does not violate the rules—is itself a violation.</p>
    <p>UntapGo may consider the content, severity, credibility, context, safety risk and account history. Possible action includes guidance, warnings, removal of content or an event, feature restrictions, suspension or account termination. Urgent safety or security action can happen before a full review. UntapGo does not promise a specific response time or outcome, and the current product does not expose a formal appeal system.</p>
  </LegalSection>
  <LegalSection id="urgent" title="10. Serious and urgent concerns">
    <p>If someone is in immediate danger, contact local emergency services. If the issue is at a store, café or other managed venue, alert staff. Preserve relevant messages or event details where safe and lawful, but do not put yourself at further risk to collect evidence.</p>
    <p>An UntapGo report is not an emergency channel. Blocking an account is not a safety plan, and UntapGo cannot physically intervene at an event. For crime, credible violence, stalking or child-safety concerns, contact the appropriate local authority in addition to reporting the account when safe.</p>
  </LegalSection>
  <LegalSection id="contact" title="11. Contact"><p>For non-emergency safety or moderation questions, contact <strong>{"{{LEGAL_CONTACT_EMAIL}}"}</strong>. The operator must confirm this address and the operational report-handling process before publication.</p></LegalSection>
</LegalPageShell>}
