import type { Metadata } from "next";
import { LegalPageShell, LegalSection } from "@/components/legal/LegalPageShell";
export const metadata:Metadata={title:"Legal Notice | UntapGo",description:"Operator, contact, hosting and intellectual-property information for UntapGo.",alternates:{canonical:"https://untapgo.com/legal-notice"}};
const toc=[["operator","Service and operator"],["contact","Contact"],["hosting","Technical providers"],["rights","Intellectual property"],["law","Jurisdiction"]].map(([id,label])=>({id,label}));
export default function LegalNoticePage(){return <LegalPageShell title="Legal Notice" introduction="The identifying and contact information for the operator of the UntapGo service." toc={toc}>
  <LegalSection id="operator" title="1. Service and operator"><p>Service name: <strong>UntapGo</strong><br/>Operator: <strong>{"{{LEGAL_ENTITY_NAME}}"}</strong><br/>Legal form: <strong>{"{{LEGAL_ENTITY_LEGAL_FORM}}"}</strong><br/>Registration number: <strong>{"{{COMPANY_REGISTRATION_NUMBER}}"}</strong><br/>Registered office: <strong>{"{{LEGAL_ENTITY_ADDRESS}}"}</strong></p><p>UntapGo is an EU-based consumer web application operated from Estonia. It helps local Magic: The Gathering players create accounts and profiles, discover and organise user-created tabletop events, coordinate seats, share selected deck information and manage attendance. Unless a listing expressly states otherwise, an event is organised by its user host rather than the UntapGo operator.</p><p>The missing company particulars must be completed from official registration records before publication. The product name is not a substitute for identifying the legal operator.</p></LegalSection>
  <LegalSection id="contact" title="2. Contact"><p>General and legal enquiries: <strong>{"{{LEGAL_CONTACT_EMAIL}}"}</strong><br/>Privacy enquiries and data-rights requests: <strong>{"{{PRIVACY_CONTACT_EMAIL}}"}</strong></p><p>No telephone number, VAT number or Data Protection Officer has been stated because the repository does not verify one.</p></LegalSection>
  <LegalSection id="hosting" title="3. Hosting and technical providers"><p>Supabase supplies account authentication and avatar storage. Mapbox supplies interactive maps, place search and geocoding. Google Firebase Cloud Messaging supplies optional web push delivery. Scryfall supplies card information and artwork used in deck features. Event pages can open a user-requested Google Maps search in a separate external service.</p><p>Frontend hosting: <strong>{"{{FRONTEND_HOSTING_PROVIDER}}"}</strong><br/>Backend hosting: <strong>{"{{BACKEND_HOSTING_PROVIDER}}"}</strong></p><p>Those hosting details are placeholders because deployment configuration was not present in the inspected frontend. Privacy roles, processing regions and contact particulars are described only after factual confirmation. More information about information handling appears in the Privacy Policy and Cookie Policy.</p></LegalSection>
  <LegalSection id="rights" title="4. Intellectual property and third-party marks"><p>UntapGo’s original branding, software, interface design and original service content are protected by applicable intellectual-property law. User content remains owned by its author, subject to the limited licence in the Terms of Service.</p><p>Magic: The Gathering, Wizards of the Coast, card names, card artwork and other third-party marks and works belong to their respective owners. Use of card data or imagery does not transfer ownership to UntapGo.</p><p><strong>UntapGo is an independent community product and is not affiliated with or endorsed by Wizards of the Coast.</strong></p></LegalSection>
  <LegalSection id="law" title="5. Governing jurisdiction"><p>This notice and use of the service are subject to <strong>{"{{GOVERNING_LAW}}"}</strong> and the courts described as <strong>{"{{COMPETENT_COURTS}}"}</strong>, without removing mandatory consumer protections or a consumer’s right to use any court made available by applicable mandatory law.</p></LegalSection>
</LegalPageShell>}
